name: Build

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore src/Lyra.Cms.slnx

      - name: Build
        run: dotnet build src/Lyra.Cms.slnx --configuration Release --no-restore

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build container image
        run: docker build -f src/Lyra.Cms.Web/Dockerfile -t lyra-cms-cms .
